EPOCHS = 1000
EPISODES_PER_EPOCH = 2
ENV_MEMORY_SIZE = 8
TAU = 0.01
NOISE_STD_DEV = 0.2
BATCH_SIZE = 1024
BUFFER_CAPACITY = 10
# BUFFER_CAPACITY = int(5e4)
# MODEL_CHECKPOINT_DIR = r'C:\Users\burov\Projects\mas-project-burov-ay2122\checkpoints'
# BUFFER_CHECKPOINT_DIR = r'C:\Users\burov\Projects\mas-project-burov-ay2122\buf-seq.pckl'
# REWARD_LOGS_PATH = r'C:\Users\burov\Projects\mas-project-burov-ay2122\reward.log'
MODEL_CHECKPOINT_DIR = r'/mnt/mas-project-burov-ay2122/checkpoints'
BUFFER_CHECKPOINT_DIR = r'/mnt/mas-project-burov-ay2122/buf.pckl'
REWARD_LOGS_PATH = '/mnt/mas-project-burov-ay2122/rewards.txt'
