EPOCHS = 1000
EPISODES_PER_EPOCH = 3
ENV_MEMORY_SIZE = 1
TAU = 0.01
NOISE_STD_DEV = 0.2
BATCH_SIZE = 16
BUFFER_CAPACITY = 1000
# BUFFER_CAPACITY = int(5e4)
MODEL_CHECKPOINT_DIR = r'C:\Users\nikita.burov\Projects\mas-project-burov-ay2122\checkpoints-dreamer'
BUFFER_CHECKPOINT_DIR = r'C:\Users\nikita.burov\Projects\mas-project-burov-ay2122\buf-2.pckl'
REWARD_LOGS_PATH = r'C:\Users\nikita.burov\Projects\mas-project-burov-ay2122\reward-dreamer.log'
LOSSES_LOGS_PATH = r'C:\Users\nikita.burov\Projects\mas-project-burov-ay2122\losses-dreamer.log'
# MODEL_CHECKPOINT_DIR = r'/mnt/mas-project-burov-ay2122/checkpoints'
# BUFFER_CHECKPOINT_DIR = r'/mnt/mas-project-burov-ay2122/buf.pckl'
# REWARD_LOGS_PATH = '/mnt/mas-project-burov-ay2122/rewards.txt'
