EPOCHS = 1000
EPISODES_PER_EPOCH = 10
ENV_MEMORY_SIZE = 8
TAU = 0.01
NOISE_STD_DEV = 0.2
BATCH_SIZE = 64
BUFFER_CAPACITY = 100000
# BUFFER_CAPACITY = int(5e4)
MODEL_CHECKPOINT_DIR = r'C:\Users\burov\Projects\mas-project-burov-ay2122\checkpoints-dreamer-pendulum-good'
BUFFER_CHECKPOINT_DIR = r'C:\Users\burov\Projects\mas-project-burov-ay2122\buf-pendulum.pckl'
REWARD_LOGS_PATH = r'C:\Users\burov\Projects\mas-project-burov-ay2122\reward-dreamer-pendulum.log'
LOSSES_LOGS_PATH = r'C:\Users\burov\Projects\mas-project-burov-ay2122\losses-dreamer-pendulum.log'
# MODEL_CHECKPOINT_DIR = r'/mnt/mas-project-burov-ay2122/checkpoints'
# BUFFER_CHECKPOINT_DIR = r'/mnt/mas-project-burov-ay2122/buf.pckl'
# REWARD_LOGS_PATH = '/mnt/mas-project-burov-ay2122/rewards.txt'
