name: opensim-rl
channels:
  - conda-forge
  - kidzik
  - defaults
dependencies:
  - freeglut=3.0.0
  - opensim=4.0.0
  - pip=21.3.1
  - python=3.6.1
  - python_abi=3.6
  - setuptools=58.0.4
  - wheel=0.37.1
  - pip:
    - async-timeout==4.0.2
    - atomicwrites==1.4.1
    - attrs==21.4.0
    - box2d-py==2.3.5
    - cachetools==4.2.4
    - certifi==2022.6.15
    - charset-normalizer==2.0.12
    - cloudpickle==2.1.0
    - colorama==0.4.5
    - cycler==0.11.0
    - dataclasses==0.8
    - deprecated==1.2.13
    - google-auth==2.9.0
    - gym==0.24.1
    - gym-notices==0.0.7
    - idna==3.3
    - mpi4py==3.1.3
    - dill==0.3.4
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - numpy==1.19.5
    - oauthlib==3.2.0
    - osim-rl==3.0.11
    - packaging==21.3
    - pillow==8.4.0
    - pluggy==1.0.0
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygame==2.1.0
    - pyparsing==3.0.7
    - pytest==7.0.1
    - python-dateutil==2.8.2
    - redis==4.3.3
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.5.4
    - six==1.15.0
    - tensorflow==2.4.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-probability==0.12.2
    - timeout-decorator==0.5.0
    - tomli==1.2.3
    - tqdm==4.64.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.9
    - werkzeug==2.0.3
    - wrapt==1.12.1
    - zipp==3.6.0


